sonar.projectKey=TruVideoCapacitorImageSdk
sonar.projectName=TruVideoCapacitorImageSdk
sonar.projectVersion=1.0

# Token you created earlier
sonar.login=sqp_ec142082da482995b1b23c1e28f87dfa107ff2f3

# Source code folder
sonar.sources=src

# Ignore build files + Capacitor native folders
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, android/**, ios/**

# Optional - for React test coverage (if using Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
